version: '3.8'

services:
  redis:
    image: redis:6.2-alpine
    container_name: redis_queue
    ports:
      - "6379:6379"

  api:
    build: .
    container_name: worker_api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/app
    ports:
      - "8008:8000"
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  worker:
    build: .
    container_name: celery_worker
    command: celery -A app.tasks.celery worker --loglevel=info
    volumes:
      - ./app:/app
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0